version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - mkdir -p build
      - cp target/*.jar build/app.jar
      - cd build && zip ../app.zip app.jar

post_build:
  commands:
    - echo Build completed on `date`

artifacts:
  files:
    - app.zip
  discard-paths: yes
